/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    AttachmentList: typeof import('./src/components/AttachmentList.vue')['default']
    BankkontoDetail: typeof import('./src/components/BankkontoDetail.vue')['default']
    CsvImportDialog: typeof import('./src/components/CsvImportDialog.vue')['default']
    DarlehenDetail: typeof import('./src/components/DarlehenDetail.vue')['default']
    DkModal: typeof import('./src/components/DkModal.vue')['default']
    FahrzeugDetail: typeof import('./src/components/FahrzeugDetail.vue')['default']
    KachelCard: typeof import('./src/components/KachelCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VertragDetail: typeof import('./src/components/VertragDetail.vue')['default']
    WohnungDetail: typeof import('./src/components/WohnungDetail.vue')['default']
  }
}
